Splitwise/Splitwise/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from webapp import views


urlpatterns = [
    url(r'^$',views.index,name='index',),
    url(r'^admin/', admin.site.urls),
    url(r'^webapp/',include('webapp.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'special/',views.special,name='special'),
    url(r'transaction/$',views.transaction,name='transaction'),
    url(r'history/$',views.history,name='history'),
    url(r'settle/$',views.settle,name='settle'),
    url(r'^n/$',views.nullify,name='nullify',),
    #url(r'^n/$',views.history,name='messages',),
]

Splitwise/webapp/urls.py
from django.conf.urls import url
from webapp import views

# SET THE NAMESPACE!
app_name = 'webapp'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),


    ]

Splitwise/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#class UserProfileInfo(models):
#    user = models.OnetoOneField(User)
#profile_pic=models.ImageField(upload_to='profile_pics'blank=True)
def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        username=self.user.username
        return self.user.username

#class Transact(models.Model):

class Transaction_Pairs(models.Model):
    person1=models.CharField(max_length=264)
    person2=models.CharField(max_length=264)
    amount=models.FloatField(null=True)


    def __str__(self):
        return self.person1 +" "+self.person2 + " "

class Transaction_history(models.Model):
    person1=models.CharField(max_length=264,default=" ")
    person2=models.CharField(max_length=264,default=" ")
    date= models.DateTimeField( auto_now_add=True, null=True)
    reason=models.CharField(max_length=264)
    amount=models.FloatField(null=True)
    def __str__(self):
        return self.person1 +" "+self.person2 + " "+self.reason

Splitwise/webapp/forms.py
from django import forms
from django.contrib.auth.models import User
from webapp.models import Transaction_Pairs
from webapp.models import Transaction_history
#from webapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields = ('username','email','password')

class TransactionForm(forms.ModelForm):

    people=forms.CharField(widget=forms.TextInput(attrs={'class':'inputField'}))
    reason=forms.CharField(widget=forms.TextInput(attrs={'class':'inputField'}))
    
    class Meta():
        model=Transaction_Pairs
        fields=('amount',)

class TransactionHistory(forms.Form):
    person_name=forms.CharField()

#class UserProfileInfoForm(forms.ModelForm):
   # class Meta():
      #  model=UserProfileInfoFormfields=('portfolio_site','profile_pic')

Splitwise/webapp/views.py
from django.shortcuts import render,redirect
from webapp.forms import UserForm

from webapp.forms import TransactionForm
from webapp.forms import TransactionHistory
from webapp.models import Transaction_Pairs
from webapp.models import Transaction_history
#from webapp.forms import UserProfileInfo
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.db.models import DateTimeField
from django.contrib import messages


#import all the views eg-from django.view.generic import(TemplateView,ListView)
def index(request):
    global person_n
    datap= Transaction_Pairs.objects.filter(person1=request.user.get_username())
    dataopp= Transaction_Pairs.objects.filter(person2=request.user.get_username())
    return render(request,'webapp/index.html',{"datap":datap,"dataopp":dataopp})
'''
    if request.GET.get('mybtn') or request.GET.get('mybtn1')  and person_n !="":
        amtr=int(request.GET.get('mytextbox'))
        obj=(Transaction_Pairs.objects.get(person1=request.user.get_username(),person2=person_n,) if Transaction_Pairs.objects.filter(person1=person_n,person2=request.user.get_username()).count()==0 else Transaction_Pairs.objects.get(person1=person_n,person2=request.user.get_username()))
        if request.GET.get('mybtn') and amtr!=0 and obj.amount!=0:
            #last if is so the value doesnt go from money owed 0 to negative
            obj.amount-=amtr
        elif request.GET.get('mybtn') and amtr==0:
            return HttpResponse("Enter an amount!") #I want it to be an alert

        elif request.GET.get('mybtn1'):
            obj.amount=0
        obj.save()



        datap= Transaction_Pairs.objects.filter(person1=request.user.get_username())
        dataopp= Transaction_Pairs.objects.filter(person2=request.user.get_username())
        person_n=""
        '''


@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered=False

    if request.method == "POST":
        user_form=UserForm(data=request.POST)
        #profile_form=UserProfileInfoForm(datap=reqest.Post)
        if user_form.is_valid():
            #and profile_frm.is_valid()
            user =user_form.save()
            user.set_password(user.password)
            user.save()
            #profile=profile_form.save(commit=False)
            #profile.user=user
            #if 'profile_pic' in request.files:
                #profile.profile_pic=request.FILES['profile_pic']
            #profile.save
            registered=True

            #print(profile_forms.errors)
    else:
        user_form=UserForm()
        #profile_form=UserProfileInfoFrom()
    return render(request,'webapp/registeration.html',{'user_form':user_form,'registered':registered})
    #add key value pair 'profile_form':profile_form,

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'webapp/login.html', {})


def transaction(request):
    numpeople=0
    amt=0
    progress=False
    if request.method == "POST":
        transact_form=TransactionForm(data=request.POST)
        if transact_form.is_valid():
            progress=True
            person1_=request.user.get_username()
            reason=request.POST["reason"]
            #now = date.datetime.now()
            amt=request.POST["amount"]
            amt1=float(amt)
            people=request.POST["people"]
            user_list=[]
            a=0
            for x in range(0,len(people)):
                if people[x]==',':
                    temp=people[a:x]
                    a=x + 1
                    user_list.append(temp)
                    temp=""
            user_list.append(people[a:])
            numpeople_=len(user_list)+1
            for i in range(1,numpeople_):
                person2_=user_list[i-1]
                contrib=(amt1)/float(numpeople_)
                t_pair_count = Transaction_Pairs.objects.filter(person1=person1_,person2=person2_).count() + Transaction_Pairs.objects.filter(person1=person2_,person2=person1_).count()
                if t_pair_count==1:
                    #obj=(Transaction_Pairs.objects.get(person1=request.user.get_username(),person2=person2_,) if Transaction_Pairs.objects.filter(person1=person2_,person2=request.user.get_username()).count()==0 else Transaction_Pairs.objects.get(person1=person2_,person2=request.user.get_username()))
                    if Transaction_Pairs.objects.filter(person1=person2_,person2=request.user.get_username()).count()==0:
                        obj=Transaction_Pairs.objects.get(person1=request.user.get_username(),person2=person2_,)
                        flag=1
                    else:
                        obj=Transaction_Pairs.objects.get(person1=person2_,person2=request.user.get_username())
                        flag=0
                    if flag==1:
                        famt1=float(obj.amount)
                    elif flag==0:
                        famt1=-float(obj.amount)
                    amt_=float(obj.amount)
                    if flag==1:
                        amt_+=contrib
                        obj.amount=amt_
                    elif flag==0:
                        famt1+=contrib
                        obj.amount=famt1*(-1.0)
                        if obj.amount<0:
                            temp=obj.person1
                            obj.person1=obj.person2
                            obj.person2=temp
                            obj.amount=famt1

                    obj.save()

                    t_pair_count=0
                elif t_pair_count==0:
                    transact=Transaction_Pairs(person1=person1_,person2=person2_,amount=contrib)
                    transact.save()
                    t_pair_count=0
                else:
                    break
                history=Transaction_history(person1=person1_,person2=person2_,reason=reason,amount=contrib)
                history.save()
        #datap= Transaction_Pairs.objects.filter(person1=request.user.get_username())
        #dataopp= Transaction_Pairs.objects.filter(person2=request.user.get_username())
        #return render(request,'webapp/index.html',{'transact_form':transact_form,'progress':progress,"datap":datap,'dataopp':dataopp})
        return redirect('index')

    else:
        transact_form=TransactionForm()
        datap= Transaction_Pairs.objects.filter(person1=request.user.get_username())
        dataopp= Transaction_Pairs.objects.filter(person2=request.user.get_username())
        return render(request,'webapp/transaction.html',{'transact_form':transact_form,'progress':progress,"datap":datap,"dataopp":dataopp})





person_n=""

def history(request):
    global person_n

    datah=Transaction_history.objects.filter(person1=request.user.get_username())
    dataopp= Transaction_history.objects.filter(person2=request.user.get_username())
    if request.method == 'POST':
        transact_history=TransactionHistory(data=request.POST)

        if transact_history.is_valid():
            person_n=request.POST["person_name"]
            if person_n=="":
                messages.error(request,'Person Not found')
                flag1=False
            else:
                flag1=True
    else:
        transact_history=TransactionHistory()
        return render(request,'webapp/history.html',{'transact_history':transact_history,"datah":datah,"dataopp":dataopp})

    datah=Transaction_history.objects.filter(person1=request.user.get_username(),person2=person_n)
    dataopp= Transaction_history.objects.filter(person2=request.user.get_username(),person1=person_n)

    if Transaction_Pairs.objects.filter(person1=request.user.get_username(),person2=person_n).count()==0 and Transaction_Pairs.objects.filter(person1=person_n,person2=request.user.get_username()).count()==0 :
        messages.error(request,'Person Not found')
        return render(request,'webapp/history.html',{'transact_history':transact_history,"datah":datah,"dataopp":dataopp})

    elif Transaction_Pairs.objects.filter(person1=person_n,person2=request.user.get_username()).count()==0:
        famt1=Transaction_Pairs.objects.get(person1=request.user.get_username(),person2=person_n,)
        flag=True
    elif Transaction_Pairs.objects.filter(person1=request.user.get_username(),person2=person_n).count()==0:
        famt1=Transaction_Pairs.objects.get(person1=person_n,person2=request.user.get_username())
        flag=False




    #famt1=(Transaction_Pairs.objects.get(person1=request.user.get_username(),person2=person_n,) and flag=1)
    if flag==True:
        famt=float(famt1.amount)
    elif flag==False:
        famt=-float(famt1.amount)
    return render(request,'webapp/history.html',{"flag":flag,"flag1":flag1, "dataopp":dataopp,"person_n":person_n,"famount":famt,"datah":datah,"transact_history":transact_history})


def nullify(request):
    global person_n
    '''
    print("HI1")
    if request.method == 'GET':
        print("HI2")

Splitwise/webapp/templates/webapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
    .bg-img {
      /* The image used */
      background-image: url('{{ STATIC_URL }}static/pics/741514.JPG');

      min-height: 50px;

      /* Center and scale the image nicely */
      background-position: center;
      /* background-repeat: no-repeat; */
      background-size: cover;

      /* Needed to position the navbar */
      position: relative;
    }
    .topnav a {
      background-image: url('{{ STATIC_URL }}static/pics/741514.JPG');
      color: #FDFEFE;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }
    </style>
    <title>SPLITWISE</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {%load static%}
    <link rel="stylesheet" href="{% static 'master.css'%}">
    </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="bg-img">
      <div class="container">
        <div class="topnav">


          {% if user.is_authenticated %}
          <ul class="nav navbar-nav">


            {# Django Home Link / Admin Link / Register Link#}
            <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'transaction' %}">New Transaction</a></li>
            <li><a class="navbar-link" href="{% url 'history' %}">Transaction History</a></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
          </ul>
          {% else %}
          <ul class="nav navbar-nav">


            {# Django Home Link / Admin Link / Register Link#}
            <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          </ul>
        <ul class="nav navbar-nav pull-right">
            <li><a class='navbar-link' href="{% url 'webapp:user_login'%}">Login</a></li>
            <li><a class="navbar-link" href="{% url 'webapp:register' %}">Sign up</a></li>

          </ul>
          {% endif %}


        </ul>

      </div>
      </div>
    </div>
    </nav>
    <div class="container">
      {% include 'webapp/messages.html' %}
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

Splitwise/webapp/templates/webapp/history.html
<!Display Transaction History>

{%extends "webapp/index.html"%}
{% block body_block %}
<style>
  @import url('https://fonts.googleapis.com/css2?family=PT+Sans:ital@1&family=PT+Serif:ital@0;1&display=swap');

  .bg-img{
    background-image: url('../../static/pics/741514.jpg');
    color: whitesmoke;
  }

  body{
    background-image: url('../../static/pics/741514.jpg');
    color: #FDFEFE;
  }

  #main-header {
    font-family: 'PT Serif', sans-serif;
  }

  table {
    font-family: 'PT Sans', sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }


  #body_info{
    font-family: 'PT Sans', sans-serif;
    color:whitesmoke
  }

  #save{
    margin-top: 20px;
    background-color: white;
    color: black;
    border: 2px solid #ABEBC6;
    transition-duration: 0.4s;
  }

  #save:hover{
    background-color: #ABEBC6;
    color: black;
  }


  #id_person_name{
    border-radius: 10px;
  }

  label{
     color: whitesmoke;
  }

  .row{
    color:whitesmoke
  }

</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<h1 id="main-header" style="text-align:center; font-size: 30px; color: wheat;";>TRANSACTION HISTORY</h1>
<br></br>
<h3 id="body_info">Filter by Name</h3>
<form method="POST" class="post-form">
  {% csrf_token %}

    <!-- {{ transact_history.as_p}} -->
    <div class="form-div">
      <div class="form_content">
          <label for="id_person_name">Person Name :</label>
          {{ transact_history.person_name }}
      </div>
    </div>

  <button id = "save" type='Submit' class="save btn btn-default">Search</button>
</form>
<br></br>

{% if user.is_authenticated %}
{%if flag1%}
<h3 id="body_info">Your net balance with {{person_n}} is {{famount}}</h3>
{%endif%}

{%if flag%}


<form action="{% url 'nullify' %}" method="get">
    {% csrf_token %}
  <input type="text" value=0 name="mytextbox" size="1"/>
  <button name="mybtn" type='Submit' value="Click" class="save btn btn-default">Money Received</button>
  <button name="mybtn1" type='Submit' value="Click" class="save btn btn-default">Full Amount Received</button>
</form>
{% endif %}
<h3 id="body_info">Do you want to settle bills?</h3>
<button id = "save" type='Submit' class="save btn btn-default" onClick="location.href='{% url 'settle'%}'">Yes</button>
<br></br>

<div class="row">
  <div class="col-md-12">

    <table>
      <thead>
        <tr>
          <th>Sr.No</th>
          <th>Date</th>
          <th>Name</th>
          <th>Amount</th>
          <th>Reason</th>
        </tr>
      </thead>
      <tbody>

        {% for i in datah %}

          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{i.date}}</td>
            <td>{{i.person2}}</td>
            <td>{{i.amount}}</td>
            <td>{{i.reason}}</td>
            </tr>
            {%endfor%}

            {% for i in dataopp %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{i.date}}</td>
                <td>{{i.person1}}</td>
                <td>-{{i.amount}}</td>
                <td>{{i.reason}}</td>
              </tr>
            {%endfor%}



      </tbody>
    </table>

  </div>
</div>

{%else%}
<h4 id="body_info">Login to view history</h4>
{% endif %}


{% endblock %}

Splitwise/webapp/templates/webapp/index.html
{% extends "webapp/base.html" %}
{% block body_block %}

<style>
  @import url('https://fonts.googleapis.com/css2?family=PT+Sans:ital@1&family=PT+Serif:ital@0;1&display=swap');

body{

  background-image: url('{{ STATIC_URL }}static/pics/741514.JPG');
  color: #FDFEFE;
}
table {
  font-family: 'PT Sans', sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}



#main-header {
  font-family: 'PT Serif', sans-serif;

}

#body_info{
  font-family: 'PT Sans', sans-serif;
}
</style>
    <h1 id="main-header" style="text-align:center; font-size: 70px;";>SPLITWISE</h1>


    {% if user.is_authenticated %}

        <h2 style="text-align:center">Welcome {{ user.username }} to your homepage!</h2>
        <br></br>
        <h3 style="font-family:'PT Sans', sans-serif;">Transaction Details:</h3>
        <div class="row">
          <div class="col-md-12">

            <table>
              <thead>
                <tr>
                  <th>Sr.No</th>
                  <th>Name</th>
                  <th>Amount</th>
                </tr>
              </thead>
              <tbody>
                {% for i in datap %}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.person2}}</td>
                    <td>{{i.amount}}</td>
                  </tr>
                {%endfor%}
                {% for i in dataopp %}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.person1}}</td>
                    <td>-{{i.amount}}</td>
                  </tr>
                {%endfor%}
              </tbody>
            </table>
          </div>
        </div>

    {% else %}
        <h2 style="text-align:center;font-family:'PT Sans', sans-serif;">Welcome to the site!</h2>
        <p id="body_info">
        Greetings from the Splitwise Team,
        </p>
        <p id="body_info">
        Ever had to face the difficulty of splitting bills while at dinner?
        </p>
        <p id="body_info">
        Worry no more, on the Splitwise webapp, you and your friends can signup for free and split bills on the go.
        </p>
        <p id="body_info">
        All transactions are stored and calculations are done within the app.
        </p>
        <p id="body_info">
        Our highlight feature is Settle. It automatically readjusts the amounts amongst your friends and settles the amounts.
        </p>
        <p id="body_info">
        For Example-
        <div id="body_info"> If A B C are three friends</div>
      </p>
      <p>

      </p>
      <p id="body_info">
        A owes B 100 dollars
      </p>
      <p id="body_info">
        B owes C 100 dollars
        </p>
        <p id="body_info">
        Then within a click our proprietary algorithm adjusts these amounts such that A now will owe C 100 dollars
        </p>
        <p id="body_info">
        Note: This works only if all the parties are part of each others friends list
      </p>
      <p id="body_info">
              Amounts being settled have to be exact.
            </p>
        <p id="body_info">

        Sign Up to Get Started!
        </p>
    {% endif %}


{% endblock %}

Splitwise/webapp/templates/webapp/login.html
{% extends 'webapp/base.html' %}
{% block body_block%}

<style>
  @import url('https://fonts.googleapis.com/css2?family=PT+Sans:ital@1&family=PT+Serif:ital@0;1&display=swap');

#main-header {
  font-family: 'PT Serif', sans-serif;
  color: wheat
}

.bg-img{
  background-image: url('../../static/pics/741514.jpg');
  color: whitesmoke;
}

body{

  background-image: url('../../static/pics/741514.jpg');
  color: black;

}

#body_info{
  color: whitesmoke;
}

#save{
  margin-top: 20px;
  background-color: white;
  color: black;
  border: 2px solid #D7BDE2 ;
  transition-duration: 0.4s;
}

#save:hover{
  background-color: #D7BDE2 ;
  color: black;
}

</style>
<body>
    <h1 id="main-header" style="text-align:center; font size: 100px";>LOGIN</h1>
    <br></br>

  <form action="{%url 'webapp:user_login' %}" method="post" style="text-align:center">
    {%csrf_token %}
    <label for="username" id="body_info">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <br></br>
    <label for="password" id="body_info">Password:</label>
    <input type="password" name="password">
    <br></br>
    <input type="submit" name="" value="Login" id="save">
   </form>
 </div>
{% endblock %}
</body>

Splitwise/webapp/templates/webapp/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

Splitwise/webapp/templates/webapp/registeration.html
{% extends "webapp/base.html" %}



{% block body_block %}
<style>

@import url('https://fonts.googleapis.com/css2?family=PT+Sans&family=PT+Serif:ital@0;1&display=swap');
  .bg-img {
  /* The image used */
    background-image: url('../../static/pics/741514.jpg');
    color: whitesmoke
  }

  body{
    background-image: url('../../static/pics/741514.jpg');
    color: black;

  }

  #main-header{
    font-family: 'PT Serif', sans-serif;
  }

  #body_info{
    font-family: 'PT Sans', sans-serif;
  }

  #save{
    margin-top: 20px;
    background-color: white;
    color: black;
    border: 2px solid #AED6F1 ;
    transition-duration: 0.4s;
  }

  #save:hover{
    background-color: #AED6F1 ;
    color: black;
  }


  #id_email{
    border-radius: 10px;
  }

  #id_password{
    border-radius: 10px;
  }

  #id_username{
    border-radius: 10px;
  }

  label{
     color: whitesmoke;
  }

  .form-div{
    margin: auto;
    width: 25%;
    padding-top: 20px;
  }

  .button{
    text-align:center;
  }


</style>
<body>
<div class="bg-img">
      {% if registered %}
        <h1 id="main-header"  style="text-align:center; font-size: 30px; color: wheat;";>Thank you for registering!</h1>
      {% else %}
        <h1 id="main-header"  style="text-align:center; font-size: 30px; color: wheat;";>Register Here</h1>
        <br></br>
        <h3 id="body_info" style="text-align:center;">Fill out the form.</h3>
        <body>

        <form enctype="multipart/form-data" class="signup" method="POST" style="font-family: 'PT Sans', sans-serif; color:black; background-image: url('{{ STATIC_URL }}static/pics/background.JPG');">
          {% csrf_token %}
          <div class="form-div">
            <div class="form_content">
                <label for="id_username">Username :</label>
                {{ user_form.username }}
            </div>

          </div>

          <div class="form-div">
            <div class="form_content">
                <label for="id_email">Email :</label>
                {{ user_form.email }}
            </div>
          </div>


          <div class="form-div">
            <div class="form_content">
                <label for="id_password">Password :</label>
                {{ user_form.password }}
            </div>
          </div>
        <div class="button">
          <input type="submit" name="" value="Register" id="save" style="text-align:center;">
        </div>

        </form>
        </body>
      {% endif %}
</div>
</body>
{% endblock %}

Splitwise/webapp/templates/webapp/transaction.html
{% extends "webapp/base.html" %}
{% block body_block %}
<style>
  @import url('https://fonts.googleapis.com/css2?family=PT+Sans:ital@1&family=PT+Serif:ital@0;1&display=swap');

  .bg-img{
    background-image: url('../../static/pics/741514.jpg');
    background-position: center;
    background-size: cover;
  }

  #main-header{
    font-family: 'PT Serif', sans-serif;
  }

  .body_info{
    text-align:center;
    font-family: 'PT Sans', sans-serif;
    color: wheat;

  }
  #id_people{
    border-radius: 10px;
  }

  #id_reason{
    border-radius: 10px;
  }

  #id_amount{
    border-radius: 10px;
  }

  label{
     color: whitesmoke;
  }

  .form-div{
    margin: auto;
    width: 25%;
    padding-top: 20px;
  }

  .form-button{
    margin: auto;
    width: 4%;
    padding-top: 20px;
  }

  #save{
    background-color: white;
    color: black;
    border: 2px solid #F5B7B1;
    transition-duration: 0.4s;
  }

  #save:hover{
    background-color: #F5B7B1;
    color: black;
  }

  #friends {
    color: whitesmoke;
  }



  .left-half {
  position: absolute;
  left: 0px;
  width: 50%;
}

.right-half {
  position: absolute;
  right: 0px;
  width: 50%;
}


</style>
  <body class="bg-img">
        <h1 id="main-header" style="text-align:center; font-size: 20px; color:wheat";>TRANSACTION FORM</h1>
      <div class="left-half">
        <h1 id="body_info" style="text-align:center; font-size: 20px; color:whitesmoke">Enter the details:</h1>

        <form method="POST" class="post-form">
          {% csrf_token %}

          <div class="form-div">
            <div class="form_content">
                <label for="id_amount">Amount :</label>
                {{ transact_form.amount }}
            </div>

          </div>

          <div class="form-div">
            <div class="form_content">
                <label for="id_people">People :</label>
                {{ transact_form.people }}
                <p style="color:white">Enter the usernames separated by a comma</p>
            </div>
          </div>


          <div class="form-div">
            <div class="form_content">
                <label for="id_reason">Reason :</label>
                {{ transact_form.reason }}
            </div>
          </div>



          <div class="form-button">
            <button id = "save" type='Submit' class="save btn btn-default">Save</button>
          </div>
        </div>
        </form>
      <div class="right-half">
        <h3 class='body_info'>Your Friends (Usernames):</h3>
        <ul>
          {%for i in datap%}
          <li id = "friends" class='body_info'>{{i.person2}}</li>
          {%endfor%}
          {%for i in dataopp%}
          <li id ="friends" fclass='body_info'>{{i.person1}}</li>
          {%endfor%}
        </ul>
      </div>
  </body>


{% endblock %}